# Generated by Django 3.2.9 on 2021-11-15 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Renew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_renew', models.CharField(max_length=255, verbose_name='TIPOS DE SEGUROS')),
                ('comments', models.TextField(blank=True, verbose_name='OBS')),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='renew',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='task.renew', verbose_name='RENOVAÇÃO'),
            preserve_default=False,
        ),
    ]
